python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 0 --upper_bound_index 100
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 100 --upper_bound_index 200
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 200 --upper_bound_index 300
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 300 --upper_bound_index 400
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 400 --upper_bound_index 500
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 500 --upper_bound_index 600
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 600 --upper_bound_index 700
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 700 --upper_bound_index 800
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 800 --upper_bound_index 900
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 900 --upper_bound_index 1000
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 1000 --upper_bound_index 1100
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 1100 --upper_bound_index 1200
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 1200 --upper_bound_index 1300
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 1300 --upper_bound_index 1400
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 1400 --upper_bound_index 1500
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 1500 --upper_bound_index 1600
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 1600 --upper_bound_index 1700
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 1700 --upper_bound_index 1800
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 1800 --upper_bound_index 1900
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 1900 --upper_bound_index 2000
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 2000 --upper_bound_index 2100
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 2100 --upper_bound_index 2200
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 2200 --upper_bound_index 2300
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 2300 --upper_bound_index 2400
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 2400 --upper_bound_index 2500
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 2500 --upper_bound_index 2600
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 2600 --upper_bound_index 2700
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 2700 --upper_bound_index 2800
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 2800 --upper_bound_index 2900
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 2900 --upper_bound_index 3000
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 3000 --upper_bound_index 3100
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 3100 --upper_bound_index 3200
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 3200 --upper_bound_index 3300
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 3300 --upper_bound_index 3400
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 3400 --upper_bound_index 3500
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 3500 --upper_bound_index 3600
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 3600 --upper_bound_index 3700
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 3700 --upper_bound_index 3800
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 3800 --upper_bound_index 3900
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 3900 --upper_bound_index 4000
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 4000 --upper_bound_index 4100
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 4100 --upper_bound_index 4200
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 4200 --upper_bound_index 4300
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 4300 --upper_bound_index 4400
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 4400 --upper_bound_index 4500
python convert_semantic_kitti.py --sequence_id "00" --lower_bound_index 4500 --upper_bound_index 4600

python convert_semantic_kitti.py --sequence_id "01" --lower_bound_index 0 --upper_bound_index 100
python convert_semantic_kitti.py --sequence_id "01" --lower_bound_index 100 --upper_bound_index 200
python convert_semantic_kitti.py --sequence_id "01" --lower_bound_index 200 --upper_bound_index 300
python convert_semantic_kitti.py --sequence_id "01" --lower_bound_index 300 --upper_bound_index 400
python convert_semantic_kitti.py --sequence_id "01" --lower_bound_index 400 --upper_bound_index 500
python convert_semantic_kitti.py --sequence_id "01" --lower_bound_index 500 --upper_bound_index 600
python convert_semantic_kitti.py --sequence_id "01" --lower_bound_index 600 --upper_bound_index 700
python convert_semantic_kitti.py --sequence_id "01" --lower_bound_index 700 --upper_bound_index 800
python convert_semantic_kitti.py --sequence_id "01" --lower_bound_index 800 --upper_bound_index 900
python convert_semantic_kitti.py --sequence_id "01" --lower_bound_index 900 --upper_bound_index 1000
python convert_semantic_kitti.py --sequence_id "01" --lower_bound_index 1000 --upper_bound_index 1100
python convert_semantic_kitti.py --sequence_id "01" --lower_bound_index 1100 --upper_bound_index 1200

python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 0 --upper_bound_index 100
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 100 --upper_bound_index 200
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 200 --upper_bound_index 300
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 300 --upper_bound_index 400
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 400 --upper_bound_index 500
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 500 --upper_bound_index 600
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 600 --upper_bound_index 700
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 700 --upper_bound_index 800
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 800 --upper_bound_index 900
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 900 --upper_bound_index 1000
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 1000 --upper_bound_index 1100
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 1100 --upper_bound_index 1200
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 1200 --upper_bound_index 1300
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 1300 --upper_bound_index 1400
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 1400 --upper_bound_index 1500
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 1500 --upper_bound_index 1600
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 1600 --upper_bound_index 1700
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 1700 --upper_bound_index 1800
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 1800 --upper_bound_index 1900
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 1900 --upper_bound_index 2000
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 2000 --upper_bound_index 2100
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 2100 --upper_bound_index 2200
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 2200 --upper_bound_index 2300
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 2300 --upper_bound_index 2400
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 2400 --upper_bound_index 2500
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 2500 --upper_bound_index 2600
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 2600 --upper_bound_index 2700
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 2700 --upper_bound_index 2800
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 2800 --upper_bound_index 2900
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 2900 --upper_bound_index 3000
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 3000 --upper_bound_index 3100
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 3100 --upper_bound_index 3200
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 3200 --upper_bound_index 3300
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 3300 --upper_bound_index 3400
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 3400 --upper_bound_index 3500
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 3500 --upper_bound_index 3600
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 3600 --upper_bound_index 3700
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 3700 --upper_bound_index 3800
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 3800 --upper_bound_index 3900
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 3900 --upper_bound_index 4000
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 4000 --upper_bound_index 4100
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 4100 --upper_bound_index 4200
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 4200 --upper_bound_index 4300
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 4300 --upper_bound_index 4400
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 4400 --upper_bound_index 4500
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 4500 --upper_bound_index 4600
python convert_semantic_kitti.py --sequence_id "02" --lower_bound_index 4600 --upper_bound_index 4700

python convert_semantic_kitti.py --sequence_id "03" --lower_bound_index 0 --upper_bound_index 100
python convert_semantic_kitti.py --sequence_id "03" --lower_bound_index 100 --upper_bound_index 200
python convert_semantic_kitti.py --sequence_id "03" --lower_bound_index 200 --upper_bound_index 300
python convert_semantic_kitti.py --sequence_id "03" --lower_bound_index 300 --upper_bound_index 400
python convert_semantic_kitti.py --sequence_id "03" --lower_bound_index 400 --upper_bound_index 500
python convert_semantic_kitti.py --sequence_id "03" --lower_bound_index 500 --upper_bound_index 600
python convert_semantic_kitti.py --sequence_id "03" --lower_bound_index 600 --upper_bound_index 700
python convert_semantic_kitti.py --sequence_id "03" --lower_bound_index 700 --upper_bound_index 800

python convert_semantic_kitti.py --sequence_id "04" --lower_bound_index 0 --upper_bound_index 100
python convert_semantic_kitti.py --sequence_id "04" --lower_bound_index 100 --upper_bound_index 200
python convert_semantic_kitti.py --sequence_id "04" --lower_bound_index 200 --upper_bound_index 300
